"""The diversity-ablation twin (Chapter 27, sec-collective-conditions).

A bigger team is a bigger jury, and Chapter 13's theorem is explicit about the
condition that makes a jury worth more than its ablest member: the errors must
be *independent*. This module ablates that condition. It starts with a panel
that shares one context --- so their errors correlate and the panel votes like
a single juror photocopied --- and decorrelates it stepwise by splitting the
evidence, until each juror reasons from its own slice. As the correlation
falls, the effective jury size rises and the majority accuracy climbs: the
jury theorem switching on, watched in slow motion.

The correlation is not assumed; it is *estimated* by simulating correlated
juror votes with a seeded generator, measuring the pairwise disagreement rate
over finite samples --- the observable a real ensemble hands you --- and
inverting the design-effect relation to recover ``rho``. Because the estimate
is measured, not algebraically round-tripped, ``rho_hat`` is a genuine noisy
figure that only *approximately* equals the value the panel was built with
(the accuracy plateau it drives is exact; the estimate carries sampling
noise). The simulation is seeded, so the whole module stays deterministic.
The lesson is the twin of the sweep's: adding members helps only while they
stay genuinely different, so past the knee further copies buy a verdict
already cast.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from foundations.algorithms.jury import effective_jury_size, p_majority


@dataclass(frozen=True)
class JuryStage:
    """One rung of the decorrelation ladder, from shared to split evidence."""

    label: str
    disagreement: float      # measured pairwise disagreement rate
    correlation: float       # rho_hat, estimated back from the disagreement
    effective_n: float       # independent-equivalent jurors under that rho
    accuracy: float          # majority accuracy at that effective size


def _label(m: int, first: int, last: int) -> str:
    if m == first:
        return "shared-context"
    if m == last:
        return "split-evidence"
    return "partly-split"


def _measure_disagreement(n: int, p: float, rho: float,
                          rng: random.Random, trials: int) -> float:
    """Simulate ``n`` correlated jurors and measure their pairwise
    disagreement rate over ``trials`` draws.

    The correlation is generated by a copying mixture: with probability
    ``rho`` a single shared vote is photocopied to every juror (perfect
    agreement, zero disagreement), and otherwise each juror votes
    independently, correct with probability ``p``. A pair therefore disagrees
    only on an independent draw, so the *expected* disagreement is
    ``d_ind (1 - rho)`` --- the design-effect relation --- but the *measured*
    rate wobbles about it with the finite sample, which is what makes the
    inverted ``rho_hat`` a genuine estimate rather than an identity.
    """
    if n < 2:
        return 0.0
    disagreeing = 0
    total = 0
    for _ in range(trials):
        if rng.random() < rho:
            votes = [rng.random() < p] * n     # one vote, photocopied
        else:
            votes = [rng.random() < p for _ in range(n)]
        for i in range(n):
            for j in range(i + 1, n):
                total += 1
                if votes[i] != votes[j]:
                    disagreeing += 1
    return disagreeing / total if total else 0.0


def jury_ablation(n: int = 7, p: float = 0.7,
                  targets: list[int] | None = None,
                  seed: int = 0, trials: int = 40_000) -> list[JuryStage]:
    """Decorrelate an ``n``-juror panel of competence ``p`` stage by stage.

    Each stage targets an effective independent count ``m`` (odd, so majority
    is unambiguous), from ``m = 1`` --- fully shared context --- up to ``m =
    n``, fully split. For each we back out the pairwise error correlation that
    produces that effective size, *simulate* a panel with that correlation to
    measure the disagreement rate an observer would see, invert it to a noisy
    estimate ``rho_hat``, and read off the majority accuracy at the effective
    size. Accuracy rises monotonically as the estimated correlation falls: the
    theorem switching on. The simulation is seeded, so results are
    reproducible.

    The accuracy column is the design-effect *reading* --- the ``m``
    independent jurors' tail sum, which Chapter 27's Exercise 3 has the
    reader reproduce analytically --- not the mixture panel's exact
    accuracy: under the photocopying mixture that is ``rho * p + (1 - rho)
    * P_n(p)``, and the reading understates it between the endpoints.
    Effective size matches the *variance* of the correlated panel, not its
    majority distribution; the instrument is priced, not free.
    """
    if targets is None:
        targets = list(range(1, n + 1, 2))  # odd effective sizes 1..n
    d_ind = 2 * p * (1 - p)                  # independent-jury disagreement
    first, last = targets[0], targets[-1]
    rng = random.Random(seed)
    stages: list[JuryStage] = []
    for m in targets:
        # The rho that makes n jurors behave like m independent ones:
        #   n_eff = n / (1 + (n - 1) rho)  =>  rho = (n - m) / (m (n - 1)).
        rho = (n - m) / (m * (n - 1)) if n > 1 else 0.0
        n_eff = effective_jury_size(n, rho)
        # Measure the disagreement from a seeded simulation, then invert the
        # design-effect relation d = d_ind (1 - rho) to estimate rho back. The
        # recovered rho_hat approximates the design rho up to sampling noise.
        disagreement = _measure_disagreement(n, p, rho, rng, trials)
        rho_hat = 1 - disagreement / d_ind if d_ind > 0 else 0.0
        accuracy = p_majority(round(n_eff), p)
        stages.append(JuryStage(_label(m, first, last), disagreement,
                                rho_hat, n_eff, accuracy))
    return stages
